Import Library

In [ ]:
import pandas as pd

Load the CSV File

In [ ]:
df = pd.read_csv("INTERN_DATASET.csv")
df.head()

,Intern_ID,Intern_Name,Domain,Mentor_Name,Tasks_Assigned,Tasks_Completed,Attendance_Percentage,Mentor_Rating,Project_Submission,Performance_Level
0,INT001,Arjun,Data Science,Rahul,15,14,97,10,Yes,Excellent
1,INT002,Divya,Data Science,Rahul,14,13,96,9,Yes,Excellent
2,INT003,Kiran,Data Science,Rahul,14,12,95,9,Yes,Excellent
3,INT004,Sneha,Data Science,Rahul,13,12,94,8,Yes,Good
4,INT005,Naveen,Data Science,Rahul,13,11,93,8,Yes,Good

Check Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Intern_ID              100 non-null    object
 1   Intern_Name            100 non-null    object
 2   Domain                 100 non-null    object
 3   Mentor_Name            100 non-null    object
 4   Tasks_Assigned         100 non-null    int64
 5   Tasks_Completed        100 non-null    int64
 6   Attendance_Percentage  100 non-null    int64
 7   Mentor_Rating          100 non-null    int64
 8   Project_Submission     100 non-null    object
 9   Performance_Level      100 non-null    object
dtypes: int64(4), object(6)
memory usage: 7.9+ KB

Check Missing Values

In [ ]:
df.isnull().sum()

Intern_ID                0
Intern_Name              0
Domain                   0
Mentor_Name              0
Tasks_Assigned           0
Tasks_Completed          0
Attendance_Percentage    0
Mentor_Rating            0
Project_Submission       0
Performance_Level        0
dtype: int64

Check Duplicate

In [ ]:
df.duplicated().sum()

np.int64(0)

Remove duplicates

In [ ]:
df = df.drop_duplicates()